# https://github.com/cncf/foundation/blob/main/policies-guidance/allowed-third-party-license-policy.md
allow-licenses:
- 'Apache-2.0'
- 'BSD-2-Clause'
- 'BSD-2-Clause-FreeBSD'
- 'BSD-3-Clause'
- 'CC-BY-4.0'
- 'CC0-1.0'
- 'ISC'
- 'LGPL-2.0-only'
- 'LGPL-2.0-or-later'
- 'LGPL-2.1-only'
- 'LGPL-2.1-or-later'
- 'LGPL-3.0-only'
- 'LGPL-3.0-or-later'
- 'LicenseRef-scancode-alliance-open-media-patent-1.0'
- 'LicenseRef-scancode-other-permissive'
- 'MIT'
- 'MPL-2.0'
- 'PostgreSQL'
- 'Python-2.0'
- 'Unlicense'
- 'X11'
- 'Zlib'
